### ISSUE TITLE
Invalid encoding?

### ISSUE THREAD

**Issue by youngmicroserf** [relue2718/onenote-duplicates-remover#10]
I'm wondering if there is anything I can do to make this work - ON 2013 W10? Here's the log... thanks!
```

EXCEPTION * 20.02.2017 13:56:59 * Unexpected Exception: System.Xml.XmlException: '�', hexidezimaler Wert 0xDE7A, ist ein ungültiges Zeichen. Zeile 2, Position 370218.
   bei System.Xml.XmlTextReaderImpl.Throw(Exception e)
   bei System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   bei System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   bei System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   bei System.Xml.XmlTextReaderImpl.ParseAttributes()
   bei System.Xml.XmlTextReaderImpl.ParseElement()
   bei System.Xml.XmlTextReaderImpl.ParseElementContent()
   bei System.Xml.XmlTextReaderImpl.Read()
   bei System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   bei System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   bei System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   bei System.Xml.XmlDocument.Load(XmlReader reader)
   bei System.Xml.XmlDocument.LoadXml(String xml)
   bei OneNoteDuplicatesRemover.OneNoteAccessor.UpdateHierarchy()
WARNING * 20.02.2017 13:56:59 * Unable to get a hierarchy.
```

**Comment by relue2718** [comment]
To my understanding, C# XML parser found some unexpected characters which are not supposed be appearing in that format. 

`bool success = instance.TryGetHierarchyAsXML(out hierarchyXmlString);`

The string variable _hierarchyXmlString_ should contain the tree hierarchy and it must be properly encoded in Unicode (it is not clear whether Microsoft internally uses UTF-8, UTF-16 LE, UTF-16 BE). Could you please check the substring near that position?  (Zeile 2, Position 370218.)

For example,
`hierarchyXmlString.Substring(370218-100, 200);`

I think this snippet (https://dotnet-snippets.de/snippet/string-in-hex-wandeln/59) is also helpful to dig down the problem.
