### ISSUE TITLE
Different computed Hash

### ISSUE THREAD

**Issue by crasschris** [relue2718/onenote-duplicates-remover#22]
Tried first on my work Win10 computer:
Microsoft® OneNote® for Microsoft 365 MSO (Version 2402 Build 16.0.17328.20346) 32-bit 
and then my personal Win11:
Microsoft® OneNote® for Microsoft 365 MSO (Version 2406 Build 16.0.17726.20078) 64-bit 

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of https://relue2718.com/static/publish/onenote_duplicates_remover/OneNoteDuplicatesRemover.application resulted in exception. Following failure messages were detected:
		+ Application manifest has either a different computed hash than the one specified or no hash specified at all. 
		+ File, OneNoteDuplicatesRemover.exe.manifest, has a different computed hash than specified in manifest.

**Comment by relue2718** [comment]
The issue has been resolved. I restored the previous version of the uploaded manifest file.
